import Providers from "./Providers";
import Navbar from "../components/Navbar";
import { Toaster } from "react-hot-toast";
import "./globals.css";


export const metadata = {
  title: "Klubo app",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="flex flex-col items-center pb-[65px]">
        <Toaster />
        <Providers>
          <div className="">{children}</div>
          <Navbar />
        </Providers>
      </body>
    </html>
  );
}
